---
# tasks file for sample-apache
- name: install pkgs
  yum: 
    name: "{{ packages }}"
    state: installed

- name: enable {{ apache_svc }}
  service:
    name: "{{ apache_svc }}"
    enabled: true
    state: started
- name: firewall enable
  firewalld:
    service: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  loop: "{{ rule }}"

- name: index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart {{ apache_svc }}

