---
- name: open ports in backend
  hosts: webservers
  become: true
  tasks:
    - name: open firewall
      firewalld:
       service: http
       permanent: yes
       immediate: yes
       state: enabled
    - add_host:
       name: backend
       servers:
        - name: "{{ ansible_fqdn }}"
          address: "{{ ansible_default_ipv4.address }}"
    - name: task of printing
      debug:
        msg: "The variable is  {{ hostvars['backend'] }}"

- name: load balance
  hosts: proxy
  become: true
  gather_facts: true
  vars:
    haproxy_backend_balance_method: 'roundrobin'
    haproxy_backend_servers: "{{ hostvars['backend']['servers'] }}"
      
   # haproxy_backend_servers:
    #  - name: serverb.lab.example.com
    #    address: 172.25.250.11
    #  - name: serverc.lab.example.com
    #    address: 172.25.250.12
  #tasks:
  #  - set_fact:
   #     haproxy_backend_servers:
   #     - name: "{{ item }}"
   #       address: "{{ hostvars[item]['default_ipv4']['addres'] }}"
   #   with_items: "{{ groups['webservers'] }}"
   # - name: print
   #   debug:
  #      msg: "The variable is {{ haproxy_backend_servers }}"
  tasks:
  - name: task of printing
    debug:
      msg: "The variable is  {{ haproxy_backend_servers }}"
  roles:
    - geerlingguy.haproxy

