---
- name: packages
  hosts: all
  become: true
  tasks:
    - name: install pkgs
      yum:
        name:
          - tcpdump
          - mailx
        state: latest
      when: inventory_hostname in groups['proxy']

    - name: install pkgs 2
      yum:
        name:
          - lsof
          - mailx
        state: latest
      when: inventory_hostname in groups['database']
