---
- name: jinja
  hosts: database
  become: true
  tasks:
    - name: template
      template:
        src: server_list.j2
        dest: /etc/server_list.txt
        owner: automation
        mode: 0600
        setype: net_conf_t
