---
- name: users
  hosts: all
  vars:
    - vault.yml
  tasks:
    - name: group1
      group:
        name: opsmgr
        state: present
    - name: group2
      group:
        name: devops
        state: present
    - name: users
      user:
        name: 
        group:
        password: "{{ dev_pass  | password_hash('sha512') }}"
      when: ansible_inventory in groups['dev'] and groups['test']
      
      user:
        name: 
        group:
        password: "{{ mgr_pass | password_hash('sha512') }}"
      when: ansible_inventory in groups['prod']
      
